import argparse
import json
import os
import traceback
from pathlib import Path
import pandas as pd
from ab.nn.util.Util import release_memory, uuid4, read_py_file_as_string

from ab.gpt.util.Const import epoch_dir, synth_dir, new_nn_file, nngpt_dir
from ab.gpt.util.NNEval import NNEval
from ab.gpt.util.Util import verify_nn_code, copy_to_lemur

# --- Default Evaluation Parameters ---
# TODO: CARRY ALL THIS STUFF TO CONST.PY
# These will be used as defaults for argparse arguments
DEFAULT_NN_TRAINING_EPOCHS = 1  # How many epochs to train the altered NN for evaluation
DEFAULT_TASK = 'img-classification'
DEFAULT_DATASET = 'cifar-10'
DEFAULT_METRIC = 'acc'

# Default hyperparameters. 'epoch' will be overridden.
# TODO: DETECT EPOCH AUTOMATICALLY
DEFAULT_LR = 0.01
DEFAULT_BATCH_SIZE = 16
DEFAULT_DROPOUT = 0.2
DEFAULT_MOMENTUM = 0.9
DEFAULT_TRANSFORM = 'norm_flip'  # A common default, used by NNEval if prm is None
DEFAULT_NN_NAME_PREFIX = "FractalNet"

def evaluate_altered_models(args: argparse.Namespace):
    """
    Evaluates neural networks generated by NNAlter.py.

    :param args: Parsed command-line arguments.
    """
    print(f"Starting evaluation of altered NNs...")
    print(f"NNAlter run epochs to scan: {args.nn_alter_epochs}")
    print(f"Each altered NN will be trained for: {args.nn_train_epochs} epochs for evaluation.")
    print(f"Base task: {args.task}, Base dataset: {args.dataset}, Base metric: {args.metric}")
    print(f"Base Hyperparameters for NNEval (before df override):")
    print(f"  LR: {args.lr}, Batch Size: {args.batch_size}, Dropout: {args.dropout}, Momentum: {args.momentum}, Transform: {args.transform}")
    print(f"Save to DB: {args.save_to_db}")

    base_nngpt_path = nngpt_dir  # out/nngpt
    
    if args.nn_alter_epochs is not None:
        num_epochs = args.nn_alter_epochs
    else:
        num_epochs = len(os.listdir(epoch_dir()))

    for i in range(num_epochs):
        # Path to the output of one NNAlter.py epoch (e.g., out/nngpt/llm/epoch/A0)
        current_alter_epoch_path = epoch_dir(i)

        # If a custom synth_dir is given, use it; otherwise build from epoch_dir
        if args.synth_dir:
            models_base_dir = Path(args.synth_dir)
        else:
            models_base_dir = current_alter_epoch_path / "synth_nn"

        if not models_base_dir.exists():
            print(f"Directory {models_base_dir} for NNAlter epoch {i} not found. Skipping.")
            continue

        print(f"\n--- Scanning NNAlter Epoch Directory: {current_alter_epoch_path} ---")
        print(f"--- Synthesized Models Directory: {models_base_dir} ---")

        for model_folder_name in os.listdir(models_base_dir):
            model_dir_path = models_base_dir / model_folder_name
            if not model_dir_path.is_dir():
                continue

            code_file_path = model_dir_path / new_nn_file
            df_file_path = model_dir_path / 'dataframe.df'  # Original model's metadata

            if not code_file_path.exists():
                print(f"Code file {new_nn_file} not found in {model_dir_path}. Skipping.")
                continue

            print(f"\n--- Evaluating Model: {model_dir_path.relative_to(base_nngpt_path)} ---")

            if not verify_nn_code(model_dir_path, code_file_path):
                print(f"Code verification failed for {code_file_path}. Skipping evaluation.")
                with open(model_dir_path / 'eval_verification_failed.txt', 'w') as f:
                    f.write("Initial code verification failed.")
                continue

            # Initialize task, dataset, metric, and prm from command-line arguments (or their defaults)
            task = args.task
            dataset = args.dataset
            metric = args.metric
            # This prm structure is consistent with LEMUR dataset's expectations for model training
            prm = {
                'lr': args.lr,
                'batch': args.batch_size,
                'dropout': args.dropout,
                'momentum': args.momentum,
                'transform': args.transform,  # Default transform from CLI
                # 'epoch' will be set explicitly later
            }
            prefix_for_db = "FractalNet"  # Default prefix
            origdf = None
            if df_file_path.exists():
                try:
                    origdf = pd.read_pickle(df_file_path)
                    # Override with values from dataframe.df if they exist
                    task = origdf.get('task', task)
                    dataset = origdf.get('dataset', dataset)
                    metric = origdf.get('metric', metric)

                    original_prm_from_df = origdf.get('prm')
                    if isinstance(original_prm_from_df, dict):
                        # Update prm with values from df, df values take precedence.
                        # This will update lr, batch, dropout, momentum, transform if they exist in original_prm_from_df,
                        # and also add any other model-specific hyperparameters from the original model.
                        prm.update(original_prm_from_df)

                    prefix_for_db = origdf.get('nn', prefix_for_db).split('-')[0]
                    print(f"  Loaded metadata from dataframe.df: task={task}, dataset={dataset}, metric={metric}")
                except Exception as e:
                    print(f"  Error loading dataframe.df from {df_file_path}: {e}. Using command-line/default parameters for task, dataset, metric, and prm structure.")
            else:
                print(f"  No dataframe.df found. Using command-line/default evaluation parameters.")

            # Crucial: set training epochs for this evaluation from args.nn_train_epochs
            # This overrides any 'epoch' value that might have come from original_prm_from_df
            prm['epoch'] = args.nn_train_epochs
            print(f"  Final parameters for NNEval: {prm}")
            print(f"  Task: {task}, Dataset: {dataset}, Metric: {metric}, Prefix: {prefix_for_db}")

            try:
<<<<<<< Updated upstream
                origdf = pd.read_pickle(df_file_path)
                resolved_task = origdf.get("task", resolved_task)
                resolved_dataset = origdf.get("dataset", resolved_dataset)
                resolved_metric = origdf.get("metric", resolved_metric)
                orig_pref = origdf["nn"].split("-")[0]
                original_prm_from_df = origdf.get("prm")
                if isinstance(original_prm_from_df, dict):
                    prm.update(original_prm_from_df)
                prefix_for_db = nn_name_prefix or (
                    origdf.get("nn", "unknown").split("-")[0]
                    if "nn" in origdf
                    else prefix_for_db
                )
                print(
                    f"  Loaded metadata from dataframe.df: "
                    f"task={resolved_task}, dataset={resolved_dataset}, metric={resolved_metric}"
                )
            except Exception as exc:
                print(
                    f"  Error loading dataframe.df from {df_file_path}: {exc}. "
                    "Using command-line/default parameters."
                )
        else:
            print("  No dataframe.df found. Using command-line/default evaluation parameters.")

        if prm_json:
            prm.update(prm_json)
            print(f"  Applied --prm_json overrides: {prm_json}")

        # Always evaluate with nn_train_epochs for this run, regardless of what
        # may have been stored in the original prm payload.
        prm["epoch"] = int(nn_train_epochs)
        # NNDataset expects a real transform name, never None.
        if prm.get("transform") is None or not isinstance(prm.get("transform"), str):
            prm["transform"] = transform if transform else TRANSFORM

        print(f"  Final parameters for Eval: {prm}")
        print(
            f"  Task: {resolved_task}, Dataset: {resolved_dataset}, "
            f"Metric: {resolved_metric}, Prefix: {prefix_for_db}"
        )

        requests.append(
            _build_eval_request(
                model_id=model_id,
                model_dir_path=model_dir_path,
                code_file_path=code_file_path,
                task=resolved_task,
                dataset=resolved_dataset,
                metric=resolved_metric,
                prm=prm,
                save_to_db=save_to_db,
                prefix_for_db=prefix_for_db,
                epoch_limit_minutes=epoch_limit_minutes,
                lemur_prefix=nn_name_prefix or orig_pref,
            )
        )

    return requests, immediate_results


def main(
    nn_name_prefix=NN_NAME_PREFIX,
    nn_train_epochs=NN_TRAIN_EPOCHS,
    only_epoch=ONLY_EPOCH,
    save_to_db=SAVE_TO_DB,
    nn_alter_epochs=NN_ALTER_EPOCHS,
    task=TASK,
    dataset=DATASET,
    metric=METRIC,
    lr=LR,
    batch=BATCH,
    dropout=DROPOUT,
    momentum=MOMENTUM,
    transform=TRANSFORM,
    stochastic_depth_prob=STOCHASTIC_DEPTH_PROB,
    norm_eps=NORM_EPS,
    norm_std=NORM_STD,
    tie_weights=TIE_WEIGHTS,
    dropout_aux=DROPOUT_AUX,
    attention_dropout=ATTENTION_DROPOUT,
    norm_momentum=NORM_MOMENTUM,
    score_thresh=SCORE_THRESH,
    nms_thresh=NMS_THRESH,
    iou_thresh=IOU_THRESH,
    detections_per_img=DETECTIONS_PER_IMG,
    topk_candidates=TOPK_CANDIDATES,
    neg_to_pos_ratio=NEG_TO_POS_RATIO,
    pretrained=PRETRAINED,
    patch_size=PATCH_SIZE,
    prm_json=PRM_JSON,
    epoch_limit_minutes=EPOCH_LIMIT_MINUTES,
    custom_synth_dir=CUSTOM_SYNTH_DIR,
    cycle=CYCLE,
    use_all_visible_gpus: Optional[bool] = None,
):
    base_nngpt_path = nngpt_dir
    if nn_alter_epochs is None:
        if epoch_dir().is_dir():
            nn_alter_epochs = len(os.listdir(epoch_dir()))
        else:
            print(f"Directory {epoch_dir()} doesn't exist", file=sys.stderr)
            nn_alter_epochs = 0

    run_summary = {"epochs": []}
    resolved_use_all_visible_gpus = _resolve_use_all_visible_gpus(use_all_visible_gpus)

    try:
        if nn_alter_epochs:
            epoch_indices = [only_epoch] if only_epoch is not None else list(range(nn_alter_epochs))
            for i in epoch_indices:
                # Track cycle number and epoch number separately. Iterative
                # pipelines may reuse a cycle label across different epoch dirs.
                current_cycle = cycle if cycle is not None else i
                current_epoch = i
                cycle_start_time = time.time()
                # Path to one NNAlter epoch output, e.g. out/nngpt/llm/epoch/A0.
                current_alter_epoch_path = epoch_dir(i)
                # Allow callers to point directly at a synth dir instead of
                # deriving it from epoch_dir().
                models_base_dir = Path(custom_synth_dir) if custom_synth_dir else synth_dir(current_alter_epoch_path)

                if not models_base_dir.exists():
                    print(f"Directory {models_base_dir} for NNAlter epoch {i} not found. Skipping.")
                    continue

                print(f"\n--- Scanning NNAlter Epoch Directory: {current_alter_epoch_path} ---")
                print(f"--- Synthesized Models Directory: {models_base_dir} ---")

                # Build eval requests first so already successful models can be
                # skipped without waking workers unnecessarily.
                requests, epoch_results = _collect_epoch_requests(
                    models_base_dir=models_base_dir,
                    nn_name_prefix=nn_name_prefix,
                    nn_train_epochs=nn_train_epochs,
                    save_to_db=save_to_db,
=======
                evaluator = NNEval(
                    model_source_package=str(model_dir_path),
>>>>>>> Stashed changes
                    task=task,
                    dataset=dataset,
                    metric=metric,
                    prm=prm,  # Pass the constructed prm
                    save_to_db=args.save_to_db,
                    prefix=prefix_for_db,
                    save_path=model_dir_path
                )
                evaluator.epoch_limit_minutes = args.epoch_limit_minutes

<<<<<<< Updated upstream
                if requests:
                    NNEvalWorkerPool.prewarm_nneval_workers(
                        use_all_visible_gpus=resolved_use_all_visible_gpus,
                        timeout_seconds=60.0,
                    )
                    entries = [{"payload": request} for request in requests]
                    worker_results = NNEvalWorkerPool.evaluate_model_entries(
                        entries,
                        use_all_visible_gpus=resolved_use_all_visible_gpus,
                    )
                    for request, worker_result in zip(requests, worker_results):
                        model_id = request["model_id"]
                        if worker_result.get("success"):
                            print(f"  Evaluation results for {model_id}: {worker_result}")
                            epoch_results.append(_write_success_outputs(request, worker_result))
                        else:
                            print(f"  Error evaluating model {model_id}: {worker_result.get('error')}")
                            epoch_results.append(_write_failure_outputs(request, worker_result))
                        release_memory()

                # Rebuild cycle_results.json from the artifacts produced in this
                # epoch directory after all worker results have been written.
                cycle_end_time = time.time()
                cycle_time_minutes = (cycle_end_time - cycle_start_time) / 60.0
                eval_results_list, model_dirs_list, successful_models, failed_models = collect_cycle_metrics(
                    models_base_dir,
                    current_alter_epoch_path,
                )
                cycle_results = generate_cycle_results(
                    cycle=current_cycle,
                    models_base_dir=models_base_dir,
                    eval_results_list=eval_results_list,
                    model_dirs_list=model_dirs_list,
                    successful_models=successful_models,
                    failed_models=failed_models,
                    cycle_time_minutes=cycle_time_minutes,
                    current_alter_epoch_path=current_alter_epoch_path,
                )
                cycle_results_path = base_nngpt_path / "cycle_results.json"
                if cycle_results_path.exists():
                    backup_path = base_nngpt_path / f"cycle_results_{i-1}.json"
                    shutil.copy2(cycle_results_path, backup_path)
                    print(f"Backup saved -> {backup_path}")
                save_cycle_results(cycle_results, cycle_results_path)
                print(
                    f"\n--- Cycle {current_cycle} (Epoch {current_epoch}) results saved to: "
                    f"{cycle_results_path} ---"
                )
                print(f"  Found {len(eval_results_list)} successful evaluations from eval_info.json files")
                print(f"  Found {len(failed_models)} failed models")
                run_summary["epochs"].append(
                    {
                        "epoch": current_epoch,
                        "cycle": current_cycle,
                        "models_base_dir": str(models_base_dir),
                        "cycle_results_path": str(cycle_results_path),
                        "model_results": sorted(epoch_results, key=lambda item: str(item.get("model_id", ""))),
                        "successful_models": len(successful_models),
                        "failed_models": len(failed_models),
                    }
                )
    finally:
        NNEvalWorkerPool.shutdown_nneval_workers()
=======
>>>>>>> Stashed changes

                eval_results = evaluator.evaluate(code_file_path)
                
                print(f"  Evaluation results for {model_folder_name}: {eval_results}")

                eval_info_data = {
                    "eval_args": evaluator.get_args(),  # This will show the prm used by NNEval
                    "eval_results": eval_results,
                    "cli_args": vars(args)
                }
                with open(model_dir_path / 'eval_info_altered.json', 'w+') as f:
                    json.dump(eval_info_data, f, indent=4, default=str)

                nn_name = uuid4(read_py_file_as_string(code_file_path))

                if args.nn_name_prefix:
                    nn_name = args.nn_name_prefix + '-' + nn_name
                copy_to_lemur(origdf, model_dir_path, nn_name)

            except Exception as e:
                error_msg = f"Error evaluating model {model_folder_name}: {e}"
                print(f"  {error_msg}")
                detailed_error = traceback.format_exc()
                print(detailed_error)
                with open(model_dir_path / 'eval_error_altered.txt', 'w+') as f:
                    f.write(f"{error_msg}\n\n{detailed_error}")
            finally:
                release_memory()


def main():
    parser = argparse.ArgumentParser(description="Evaluate Neural Networks generated by NNAlter.py.")
    parser.add_argument(
        '-nae', '--nn_alter_epochs', type=int, default=None,
        help="Number of epochs NNAlter.py was run for (e.g., if NNAlter's -e was 8, use 8 here)."
    )
    parser.add_argument(
        '-nte', '--nn_train_epochs', type=int, default=DEFAULT_NN_TRAINING_EPOCHS,
        help=f"Number of epochs to train each altered NN during evaluation (default: {DEFAULT_NN_TRAINING_EPOCHS})."
    )

    # Configurable evaluation parameters
    parser.add_argument(
        '--task', type=str, default=DEFAULT_TASK,
        help=f"Default task for NNEval if not in dataframe.df (default: {DEFAULT_TASK})."
    )
    parser.add_argument(
        '--dataset', type=str, default=DEFAULT_DATASET,
        help=f"Default dataset for NNEval if not in dataframe.df (default: {DEFAULT_DATASET})."
    )
    parser.add_argument(
        '--metric', type=str, default=DEFAULT_METRIC,
        help=f"Default metric for NNEval if not in dataframe.df (default: {DEFAULT_METRIC})."
    )

    # Configurable hyperparameters (part of prm dictionary for NNEval)
    parser.add_argument(
        '--lr', type=float, default=DEFAULT_LR,
        help=f"Learning rate for NNEval if not in dataframe.df's prm (default: {DEFAULT_LR})."
    )
    parser.add_argument(
        '--batch_size', type=int, default=DEFAULT_BATCH_SIZE,
        help=f"Batch size for NNEval if not in dataframe.df's prm (default: {DEFAULT_BATCH_SIZE}). Stored as 'batch' in prm."
    )
    parser.add_argument(
        '--dropout', type=float, default=DEFAULT_DROPOUT,
        help=f"Dropout rate for NNEval if not in dataframe.df's prm (default: {DEFAULT_DROPOUT})."
    )
    parser.add_argument(
        '--momentum', type=float, default=DEFAULT_MOMENTUM,
        help=f"Momentum for NNEval if not in dataframe.df's prm (default: {DEFAULT_MOMENTUM})."
    )
    parser.add_argument(
        '--transform', type=str, default=DEFAULT_TRANSFORM,
        help=f"Default transform for NNEval if not in dataframe.df's prm (default: {DEFAULT_TRANSFORM}). Stored as 'transform' in prm."
    )

    # Other NNEval options
    parser.add_argument(
        '--save_to_db', action=argparse.BooleanOptionalAction, default=True,
        help="Whether to save evaluation results to the database (enables with --save-to-db, disables with --no-save-to-db; default: enabled)."
    )

    parser.add_argument(
        '--nn_name_prefix', type=str, default=DEFAULT_NN_NAME_PREFIX,
        help=f"Default neural network name prefix (default: {DEFAULT_NN_NAME_PREFIX})."
    )
    # Custom synth_dir
    parser.add_argument(
    '--synth_dir', '--synth_nn', dest='synth_dir', type=str, default=None,
    help="Custom directory containing generated models (you can use --synth_dir or --synth_nn)"
    )

    parser.add_argument(
    '--epoch_limit_minutes', type=int, default=30,
    help="Max minutes allowed per epoch (default: 30)."
    )

    args = parser.parse_args()
<<<<<<< Updated upstream
    prm_json_dict = None
    if args.prm_json:
        try:
            prm_json_dict = json.loads(args.prm_json)
        except json.JSONDecodeError as exc:
            print(f"Error parsing --prm_json: {exc}", file=sys.stderr)
            sys.exit(1)
    print("Starting evaluation of altered NNs...")
    print(f"NNAlter run epochs to scan: {args.nn_alter_epochs}")
    print(f"Each altered NN will be trained for: {args.nn_train_epochs} epochs for evaluation.")
    print(f"Base task: {args.task}, Base dataset: {args.dataset}, Base metric: {args.metric}")
    print("Base Hyperparameters for NNEval (before df override):")
    print(
        f"  LR: {args.lr}, Batch Size: {args.batch_size}, Dropout: {args.dropout}, "
        f"Momentum: {args.momentum}, Transform: {args.transform}"
    )
    print(f"Save to DB: {args.save_to_db}")
    print(f"Prefix for the names of generated neural network: {args.nn_name_prefix}")

    main(
        nn_name_prefix=args.nn_name_prefix,
        nn_train_epochs=args.nn_train_epochs,
        only_epoch=args.only_epoch,
        save_to_db=args.save_to_db,
        nn_alter_epochs=args.nn_alter_epochs,
        task=args.task,
        dataset=args.dataset,
        metric=args.metric,
        lr=args.lr,
        batch=args.batch_size,
        dropout=args.dropout,
        momentum=args.momentum,
        transform=args.transform,
        stochastic_depth_prob=args.stochastic_depth_prob,
        norm_eps=args.norm_eps,
        norm_std=args.norm_std,
        tie_weights=args.tie_weights,
        dropout_aux=args.dropout_aux,
        attention_dropout=args.attention_dropout,
        norm_momentum=args.norm_momentum,
        score_thresh=args.score_thresh,
        nms_thresh=args.nms_thresh,
        iou_thresh=args.iou_thresh,
        detections_per_img=args.detections_per_img,
        topk_candidates=args.topk_candidates,
        neg_to_pos_ratio=args.neg_to_pos_ratio,
        pretrained=args.pretrained,
        patch_size=args.patch_size,
        prm_json=prm_json_dict,
        epoch_limit_minutes=args.epoch_limit_minutes,
        custom_synth_dir=args.custom_synth_dir,
        cycle=args.cycle,
    )
=======

    evaluate_altered_models(args)

if __name__ == "__main__":
    main()

>>>>>>> Stashed changes
